### ISSUE TITLE
Slider update problem

### ISSUE THREAD

**Issue by WitkowskiMichau** [Vonage/vivid#1012]
**Describe the bug**
We Started using slider months ago, it was working perfectly till the last one or two updates. (Haven't noticed before)
After updating the value of the slider, the value on hover is updated. However not the slider itself. The dot is not moving accordingly. 
Dot is updated after refreshing the whole page

**To Reproduce**
After updating the value of the slider, the value on hover is updated. However not the slider itself. The dot is not moving accordingly. 

**Expected behavior**
After value update, both values on hover and dot are updated.

**Screenshots**
![Screenshot 2021-08-09 at 14 50 52](https://user-images.githubusercontent.com/5145962/128710306-74e1648d-4a48-4755-aa1d-f24306b4a0d4.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser  Chrome
 - Version: 91.0.4472.164 (

**Additional context**
We use this component in react app.

**Comment by yinonov** [comment]
refactored by Material. handled in #1071

**Comment by martynfrank** [comment]
Does that refactor mean this is now fixed? @yinonov
