### ISSUE TITLE
[Tooltip] 1st draft

### ISSUE THREAD

**Issue by yinonov** [Vonage/vivid#1125]
# Tooltips are highly requested across apps.

Alternatively, a more accessible & scalable UX would be to use **popup tips**.
As [described here](https://www.nngroup.com/articles/tooltip-guidelines), if used cautiously, both tips can be used.

personally I believe having both features is bound to unintentional abuse as design & WCAG guidelines tend to fade.

recent design discussion showed popup tips as a favored candidate

Let's break down the elements structure to
## Tips
- focusable / tab-able **icon** reflecting it haspopup state
- inner **tooltips** to anchor to icon

**Comment by rinaok** [comment]
https://github.com/popperjs/popper-core

https://shoelace.style/components/tooltip?id=examples

**Comment by jshenkman** [comment]
Design 
https://www.figma.com/file/r8OYLPmRmDqfLKt6KHdJDB/Vivid-UI-Kit---2.0?node-id=1968%3A549

**Comment by jshenkman** [comment]
https://www.carbondesignsystem.com/components/tooltip/accessibility

Carbon has a good explanation about a11y consideration and a good example for implementation - using the variant 'Icon tooltip'

**Comment by rachelbt** [comment]
- add dismissible property for the X button
- component structure:
-- basic  - can have title or link and can have X button 
--extended - can have - title + text + link or button & X button (have extra padding)

**Comment by yinonov** [comment]
another ref to toggletips
https://inclusive-components.design/tooltips-toggletips/

**Comment by rachelbt** [comment]
creating basic tooltip based on popup component.:
https://tmp.dev.vivid.vonage.com/1223/index.html?path=/story/alpha-components-tooltip--introduction
