### ISSUE TITLE
[button-toggle-group] design update

### ISSUE THREAD

**Issue by yinonov** [Vonage/vivid#1139]
design to follow
https://www.figma.com/file/r8OYLPmRmDqfLKt6KHdJDB/Vivid-UI-Kit---2.0?node-id=1915%3A1490

![image](https://user-images.githubusercontent.com/7512792/144129164-8e2e6d2f-6797-4df9-bfd3-1c78e5f503ef.png)
![image](https://user-images.githubusercontent.com/7512792/144129180-7be357e9-90fd-4f5f-9c50-38ffa43ca49c.png)

**Comment by rachelbt** [comment]
env:
https://tmp.dev.vivid.vonage.com/1141/index.html?path=/story/components-button-toggle-group--basic-or-accent
