### ISSUE TITLE
[Button] add stacked layout

### ISSUE THREAD

**Issue by jshenkman** [Vonage/vivid#1156]
![image](https://user-images.githubusercontent.com/15140652/147504721-3e6448e4-3944-4dbc-898d-ba9727b6f8dc.png)

**Comment by jshenkman** [comment]
You can find the design here

we will want to add support to the following -

trailing & leading icon
rounded & pilled shape

**Comment by yinonov** [comment]
Does stack correlate with dense & enlarged or any other button variants?

**Comment by jshenkman** [comment]
> Does stack correlate with dense & enlarged or any other button variants?

Yes, we will have also the 3 sizes.
So same properties for padding and spacing, for shape (border-radius), connotation, and all properties actually except for 'text only'

**Comment by rachelbt** [comment]
stacked:
https://tmp.dev.vivid.vonage.com/1174/index.html?path=/story/components-button--stacked

Mixed sizes - you can change them all to pill, connotation and stacked
https://tmp.dev.vivid.vonage.com/1174/index.html?path=/story/components-button--stacked
