### ISSUE TITLE
Expansion Panel outlined option

### ISSUE THREAD

**Issue by rachelbt** [Vonage/vivid#1161]
add an `appearance: outlined` for outlined option:
![image](https://user-images.githubusercontent.com/7512792/147072283-10fbe7d0-7003-4a34-bca4-59e15ab50c4d.png)
this option is not needed when the `vwc-expansion-panel` is nested inside `wvc-accordion`

**Comment by yinonov** [comment]
it can still be used with accordion. the problem having multiple appearances is the lenience it introduces

**Comment by rachelbt** [comment]
StoryBook:
https://tmp.dev.vivid.vonage.com/1162/index.html?path=/story/alpha-components-accordion--outlined-expansion-panel
