### ISSUE TITLE
[Switch] re-design

### ISSUE THREAD

**Issue by jshenkman** [Vonage/vivid#1171]
Apply re-design to switch component, notice [Light theme](https://www.figma.com/file/r8OYLPmRmDqfLKt6KHdJDB/Vivid-UI-Kit---2.0?node-id=9712%3A52095) and [Dark theme ](https://www.figma.com/file/r8OYLPmRmDqfLKt6KHdJDB/Vivid-UI-Kit---2.0?node-id=9742%3A52285), they are not the same in both themes.

**Comment by yinonov** [comment]
I suggest u add another hypothetical theme to see how it complicates things. This might require another semantic variable we haven't defined yet.

Components styles only refer to tokens and has no contextual awareness.

**Comment by rachelbt** [comment]
https://files.slack.com/files-pri/T02NNHD8S-F02SDCUJ71P/1e7314370f2fc4e2d3ea06dd61068917.png

**Comment by rachelbt** [comment]
Design VS CSS:
![image](https://user-images.githubusercontent.com/7512792/147729935-2de803ea-45e3-403b-922a-dca80a9400b0.png)

**Comment by rachelbt** [comment]
StoryBook:
https://tmp.dev.vivid.vonage.com/1184/index.html?path=/story/components-switch--basic

**Comment by rachelbt** [comment]
Removed the connotation.success option
