### ISSUE TITLE
[elevation] sharp & rounded shape

### ISSUE THREAD

**Issue by rachelbt** [Vonage/vivid#1179]
Remove the css-variables that allow customers to change the elevation border-radius and alternatively hand them 2 options: sharp (border-radius:0) and 6px border radius which is the default option

**Comment by rachelbt** [comment]
@jshenkman - do our customers need the option for "open" value for border-radius or sharp & rounded?

**Comment by jshenkman** [comment]
from design perspective, we allow only 6px.. we never got a request for different border radio, so I think we can lock it down :)
