### ISSUE TITLE
[snackbar]: header doesn't show in non legacy mode

### ISSUE THREAD

**Issue by YonatanKra** [Vonage/vivid#1191]

**Comment by rachelbt** [comment]
@jshenkman:
https://tmp.dev.vivid.vonage.com/1192/index.html?path=/story/components-snackbar--action

**Comment by yinonov** [comment]
![image](https://user-images.githubusercontent.com/15140652/149668427-a2122858-b76a-4987-a11a-12f7285e95d2.png)

**Comment by rachelbt** [comment]
> 

why? the header is an "open field" can be any title to the body of the snackbar

**Comment by yinonov** [comment]
A great man once said
> I’d say those additional texts are redundant or add nothing necessary (given every word takes effort to read)

> Perfection is achieved, when there's nothing more to take away

that's just my statement for the record. we battled this issue and there's no significant conclusion other than most examples we've seen really add nothing.

**Comment by jshenkman** [comment]
Few design comments - 
1. Change description text in all variants to body-1 (currently it's body-2)
2. Change top&bottom padding to 16px (currently 18px)
3. In the "Action" story (with the header and green icon) the icon seems smaller than 24px, in the other stories icon size looks good! 

<img width="707" alt="Action" src="https://user-images.githubusercontent.com/67224525/151397298-a424872f-07da-4d04-aed8-124d42fb8883.png">
<img width="699" alt="Basic" src="https://user-images.githubusercontent.com/67224525/151397309-0065a1ff-4b27-4c05-869b-a5b13a59c469.png">

**Comment by rachelbt** [comment]
@jshenkman all is fixed:
https://tmp.dev.vivid.vonage.com/1192/index.html?path=/story/components-snackbar--action

**Comment by jshenkman** [comment]
Looks great!! approved :)
