### ISSUE TITLE
[menu] integrate elevation

### ISSUE THREAD

**Issue by yinonov** [Vonage/vivid#1193]
dark theme design of menu miss elevation
![image](https://user-images.githubusercontent.com/15140652/149153582-10a6257b-13bf-4c34-9e0a-2501895d8324.png)

**Comment by rachelbt** [comment]
All tough it is still using surface and not elevation- the ui problem was solved:
https://vivid.vonage.com/?path=/story/components-menu--with-vwc-list-item.
