### ISSUE TITLE
[vwc-datepicker] Hour selector wrongly positioned

### ISSUE THREAD

**Issue by kubafedoruk** [Vonage/vivid#1198]
**Describe the bug**
When using vwc-datepicker in our UI we see that the hour selector is not positioned correctly - it's not aligned with date picker.

**To Reproduce**
1. Go to User Admin UI - https://itg-test.nvmtest.net/CallCentre/portal/useradmin/schedules
2. Click on Date Picker
3. See error

**Expected behavior**
Time picker should be aligned like on StoryBook - https://vivid.vonage.com/?path=/story/alpha-components-datepicker--time&args=enableTime:;noCalendar:

**Screenshots**
![image](https://user-images.githubusercontent.com/31614161/149778248-1a7cc006-7a9c-435e-8e00-580c503da20a.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 97.0.4692.71

**Comment by yinonov** [comment]
can u please share limited credentials to access the admin?

**Comment by kubafedoruk** [comment]
> can u please share limited credentials to access the admin?

passes send via slack

**Comment by yinonov** [comment]
side note - weekday select can be achieved by `button-toggle-group`
vivid.vonage.com/1172/index.html?path=/story/components-button-toggle-group--multi
![image](https://user-images.githubusercontent.com/15140652/150291344-f94835b1-5520-414c-8bab-f993eafd1b86.png)

**Comment by rachelbt** [comment]
Hi, there's a Div with position:relative that causes the bug - I didn't see any need for that property,
if removed the date-picker will be OK:
![image](https://user-images.githubusercontent.com/7512792/150300183-a3437644-a7df-4545-b4c5-98e9aa1809c8.png)

**Comment by yinonov** [comment]
do note that datepicker is **_deprecated_** and not maintain due to its lack of compliance with vivid / web components standards (e.g. encapsulation which causes the above).

feel free to reopen if need
