### ISSUE TITLE
[Side-Drawer] namespace event handlers

### ISSUE THREAD

**Issue by rinaok** [Vonage/vivid#1199]
In light of the [discussion](https://vonage.slack.com/archives/C013F0YKH99/p1642418419050400) in our slack channel about the event namespaces, we should decide if we should:

- Add namespace to the dispatch events, for example: vvd-side-drawer:closed or vwc-side-drawer:closed.

or

- Remove the opened and closed dispatch events completely from side-drawer.

**Comment by yinonov** [comment]
a use-case where we may need to consider sticking to event listeners would be a `tags-set`.
`tags-set` need to keep a state of `tag`s interactions by user (removed, selected etc').
Where a single `tag` should propagate its removal to a state managing parent, event listener would be ideal.

take the following shoelace example
```html
<div class="tags-removable">
  <sl-tag size="small" removable>Small</sl-tag>
  <sl-tag size="medium" removable>Medium</sl-tag>
  <sl-tag size="large" removable>Large</sl-tag>
</div>

<script>
  const div = document.querySelector('.tags-removable');

  div.addEventListener('sl-remove', event => {
    const tag = event.target;
    tag.style.opacity = '0';
    setTimeout(() => tag.style.opacity = '1', 2000);
  });
</script>

<style>
  .tags-removable sl-tag {
    transition: var(--sl-transition-medium) opacity;
  }
</style>
```
