### ISSUE TITLE
Select component is hidden inside DataGrid

### ISSUE THREAD

**Issue by agieralt** [Vonage/vivid#1201]
**Describe the bug**
Posted here:
(https://vonage.slack.com/archives/C013F0YKH99/p1642607108078600)
Select component, when expanded, is completely hidden inside cell of DataGrid.
![image](https://user-images.githubusercontent.com/48126943/150318307-b6d81bbb-dfa1-41c3-b9ff-4d78d76d5bd5.png)

**To Reproduce**
1. Create DataGrid component
2. Create CellRenderer that shows Select component
3. Click on Select

**Expected behavior**
I'd like to see expanded list of Select. (like in native one)
![image](https://user-images.githubusercontent.com/48126943/150318535-da34a9d1-bf2d-46b4-a62c-58c344e141b8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 97.0.4692.71

**Comment by agieralt** [comment]
I've also tried to fix this with code that @k-paxian shared with me. Although it helped in his case, did not resolve mine :(

`const createVaadinGridStylePatchElement = () => {
  // This patch is needed to show slider tooltips uncropped by the grid
  const styleElement = document.createElement('style')
  styleElement.innerHTML = `
    #header {
      z-index: 0;
    }
    [part~='cell'] ::slotted(vaadin-grid-cell-content) {
      overflow: visible;
    }`
  return styleElement
}

export const vwcDataGridRefFunction = gridElement =>
  setTimeout(() => {
    gridElement?.shadowRoot
      .querySelector('vaadin-grid')
      .shadowRoot.append(createVaadinGridStylePatchElement())
  }, 0)`

**Comment by rachelbt** [comment]
For vivids: 
there are actually 2 issues that are causing it: 
1. the TD has overflow-hidden that hides the select.
2. each TR is positioned absolute - that causes a new layer stacking to each TR

**Comment by agieralt** [comment]
@rachelbt Looks promising, after changing both properties looks like this:
![image](https://user-images.githubusercontent.com/48126943/150333228-0b36d0da-7804-42c7-b249-606913cdb155.png)
Do you know what I could do to prevent Selects from hiding opened lists?

**Comment by yinonov** [comment]
This may introduce other layout / styling bugs

see
openui/open-ui#443

**Comment by rachelbt** [comment]
> Thank you!! @rachelbt Looks promising, after changing both properties looks like this: ![image](https://user-images.githubusercontent.com/48126943/150333228-0b36d0da-7804-42c7-b249-606913cdb155.png) Do you know what I could do to prevent Selects from hiding opened lists?

I wasn't suggesting a solution but pointing out the issue here when the bug will be tended :)
