### ISSUE TITLE
[dialog] Dialog Close Button overlaps with Dialog Heading

### ISSUE THREAD

**Issue by dvelluto** [Vonage/vivid#1208]
The close icon is overlapping with the heading if the text is long enough.

**To Reproduce**
1. Go to[ 'Dialog Storybook page with Close button'](https://dev.vivid.vonage.com/?path=/story/components-dialog--close-button&args=close-button:true;heading:This+is+modal+title+collapsing+with+close+button)
2. Set heading string to something long like "This is modal title collapsing with close button"
3. Open the modal dialog

**Expected behavior**
Some space between heading and close button to avoid overlap

**Screenshots**

![image](https://user-images.githubusercontent.com/57232860/150748968-24883a30-c18a-4edf-bf53-3e6e7750d63d.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by yinonov** [comment]
@Vonage/vivid-core that's one of those cases where a common (private) layout component would reinforce stable layout.
common to card, dialog, popup etc'.

**Comment by rachelbt** [comment]
@jshenkman :
https://tmp.dev.vivid.vonage.com/1209/index.html?path=/story/components-dialog--close-button&args=close-button:true;heading:This+is+a+modal+window+with+a+close+button
