### ISSUE TITLE
[Dialog] add support for position-top

### ISSUE THREAD

**Issue by jshenkman** [Vonage/vivid#1215]
In modal component, we would want to allow the following positioning - 
1. position-center - currently the only option available
2. position-top - new request. 

The request came from VR - VBC admin product for modal with changing sizes, so the position will stay fixed as the modal changes.

**Comment by rachelbt** [comment]
@jshenkman 
Story-book:
https://tmp.dev.vivid.vonage.com/1226/index.html?path=/story/components-dialog--top-position&args=topPosition:true
