### ISSUE TITLE
[Accordion] redesign and specification

### ISSUE THREAD

**Issue by jshenkman** [Vonage/vivid#1218]
There are a lot of requests for varients and special customization to the accordion components, we need to redefine the component specification, layout, API, and design

**Comment by jshenkman** [comment]
We currently support 2 size variants (default & dense) and 3 layout variants in each, as shown - 

![Screen Shot 2022-01-26 at 13 58 05](https://user-images.githubusercontent.com/67224525/151159195-d9bfa9ff-ba6f-4405-96ed-5ac4481b5163.png)

**Comment by yinonov** [comment]
can we deprecate `indicatoriconset`?
if must, maybe `expanded-icon`, `collapsed-icon` would be ideal...

**Comment by yinonov** [comment]
regarding a request asking for a recursive expansion-panel, would a tree make more sense?
https://explore.fast.design/components/fast-tree-view
