### ISSUE TITLE
[accordion] wrap the button with headline

### ISSUE THREAD

**Issue by rachelbt** [Vonage/vivid#1228]
The Button in the expansion panel need to be wrapped with a `H` tag for better accessibility. 
We will use the `h3` tag as our default but we need to allow our consumers to be able to change the headline number - because the headline need be aligned with the page hierarchy.

relevant links:
[W3C example](https://www.w3.org/TR/wai-aria-practices-1.2/examples/accordion/accordion.html)
[slackDS](https://design-systems.slack.com/archives/C1RT7RBQV/p1643796233254929)

```
<expansion-panel>
  <h3>
    <button><button>
  </h3>
  <div>content</div>
</expansion-panel>
```

**Comment by rachelbt** [comment]
For Vivids: css - the headline need to get a class and: `padding: 0; margin: 0;`

**Comment by yinonov** [comment]
relates to #1218

**Comment by yinonov** [comment]
most libs either don't wrap the button with an `Hx` tag or they statically wrap it with `H3`.

but here’s an interesting simple practice where fast-foundation introduce a plain div with compensating with aria attributes to have it dynamically set

![image](https://user-images.githubusercontent.com/15140652/152697877-7296961f-4439-478f-9d4e-b34e3c490c77.png)

https://github.com/microsoft/fast/blob/3337629dc557dba8b893038597ee3465f58f4dab/packages/web-components/fast-foundation/src/accordion-item/accordion-item.template.ts#L16-L21

**Comment by rachelbt** [comment]
> most libs either don't wrap the button with an `Hx` tag or they statically wrap it with `H3`.
> 
> but here’s an interesting simple practice where fast-foundation introduce a plain div with compensating with aria attributes to have it dynamically set
> 
> ![image](https://user-images.githubusercontent.com/15140652/152697877-7296961f-4439-478f-9d4e-b34e3c490c77.png)
> 
> https://github.com/microsoft/fast/blob/3337629dc557dba8b893038597ee3465f58f4dab/packages/web-components/fast-foundation/src/accordion-item/accordion-item.template.ts#L16-L21
> 
> I recommend doing the same

the H tag is better than the aria-level. @YonatanKra found a way for us to wrap the button with H tag :)

**Comment by yinonov** [comment]
How is it better? Obviously always use plain html when possible but here the solution feels a little bit overkill.
We can measure some ATs to conclude how custom roles are reflected

**Comment by YonatanKra** [comment]
> How is it better? We should always prefer plain html when possible but here the solution feels a little bit overkill.
> We can measure some ATs to conclude how custom roles are reflected

![Screenshot_20220207-074520_Brave.jpg](https://user-images.githubusercontent.com/6459899/152731317-9d8369f1-4f86-4036-b7e3-6b9994738762.jpg)
This is from MDN @yinonov @rachelbt

**Comment by yinonov** [comment]
> _Don’t use ARIA, use native HTML instead_
That is said on any aria usage

**Comment by yinonov** [comment]
seen this?
https://stackoverflow.com/a/59683415/3027703
