### ISSUE TITLE
Alternative to Volta's Color Scheme

### ISSUE THREAD

**Issue by yonatanaftali** [Vonage/vivid#1242]
Hey,

Using **Volta**, there are many possible colors for icons, for example:

![image](https://user-images.githubusercontent.com/57040227/154299488-3d91c197-c69b-4dfc-9a34-18ef284af114.png)

However using Vivid, I could only see the 6 connotations colors:

![image](https://user-images.githubusercontent.com/57040227/154299806-4c983329-9ac4-4cc2-bd6e-623283ed0240.png)

We'd expect to have the same color options in Vivid, as in Volta.
@Roee-Malis @rottenbergnirvon @mordechaiswissa FYI.

**Comment by rachelbt** [comment]
I'm not sure that Vivid suppose to support all the colors that were in Volta.
One of the Design-system goals is to unify and purify the color scheme to match Vonage branding, accessibility and more.
You can however change an icon color if you're using it as inline - than it inherit the color of the text.
It is important to use the colors via the design system tokens and not hard coded colors. for example: `--vvd-color-cta-30`

**Comment by yinonov** [comment]
Just to validate, what are you asking to color? Plain text?

**Comment by yonatanaftali** [comment]
Icon

**Comment by yinonov** [comment]
would that fit?
<img width="93" alt="image" src="https://user-images.githubusercontent.com/15140652/154330093-77b98680-2818-43c1-9429-5a28fd6c4119.png">

https://codepen.io/yinonov/pen/rNYYoNN

note this isn't a valid interface for icon. but is a reliable workaround until we define neutral shades for icon

**Comment by yonatanaftali** [comment]
Not exactly because if I have other icons in the same file I don't want all of them to be colored this way. I need to have a way to control one specific icon color, the same way I can do that with Volta's class method.

**Comment by rachelbt** [comment]
you can give the component class or ID to target the color....

**Comment by yonatanaftali** [comment]
Of course, I can, but then if I need this color in a different file, I'll need to add this class again and get duplicate code - and we're only talking about one specific color here.
Whereas when using Volta, I can just use the class Vlt-<color>-<shade> and that's it. I'd expect Vivid to offer similar functionality.

**Comment by yinonov** [comment]
Please share the design in the slack channel so we can take it from there

**Comment by yinonov** [comment]
Design shared in slack included a whole feature design (rather than individual component). the assumption is this relate to _list-items_ icons with what might need to be handled by the @Vonage/vivid. or is part of the #1243.

note: Vivid will not expose all types of colors as in Volta for ergonomic development reasons.

Please reopen if issue is still relevant and not covered by the above
