### ISSUE TITLE
[Text-field] Number input

### ISSUE THREAD

**Issue by jshenkman** [Vonage/vivid#1244]
Request from AI - Valentina

**Is your feature request related to a problem? Please describe.**
Number input is a two-segment UI control used to incrementally increase or decrease a numeric value. The two buttons are placed farther apart and allow for easier selection.  For horizontal steppers, plus and minus signs usually work best as labels for the step segments.

**Describe the solution you'd like**
 Ability to set the most frequently selected value as a stepper default. Ability to the quick entry of a number using a text field along with stepper buttons on the sides for adjustment. Block words typing in stepper field. Selecting a value greater than set or less than set should be disabled.

**Describe alternatives you've considered**
[Design proposed by Valentina - ](https://www.figma.com/file/6GHXjVymdwGOWYmESY3Ex6/%F0%9F%9A%80-General-Behavior-V2_Exploration?node-id=850%3A221992)
![Screen Shot 2022-02-27 at 12 07 37](https://user-images.githubusercontent.com/67224525/155878134-074c79ef-b266-4fa9-8194-3ffe89893c3d.png)

**Additional context**
Examples from other design systems:

1. [Carbon](https://www.carbondesignsystem.com/components/number-input/usage/) 
![Screen Shot 2022-02-27 at 12 09 00](https://user-images.githubusercontent.com/67224525/155878198-018cdc14-4d7f-4e5e-ac80-be86aa0dd9cb.png)

2. [Shopify](https://polaris.shopify.com/components/forms/text-field#navigation)
![Screen Shot 2022-02-27 at 12 12 09](https://user-images.githubusercontent.com/67224525/155878292-56133258-ed38-409d-98cc-fe386d58d19b.png)

3. [Spectrum](https://opensource.adobe.com/spectrum-web-components/components/number-field/)
![Screen Shot 2022-02-27 at 12 58 45](https://user-images.githubusercontent.com/67224525/155879683-846e300a-1a35-4ab3-91c6-f6810318613e.png)

**Comment by jshenkman** [comment]
We can currently support this - 
![image](https://user-images.githubusercontent.com/67224525/155878529-c15e5661-7fdd-458a-8597-b162ff64fdb5.png)

**Comment by yinonov** [comment]
what's the conclusion here? which of the designs above are we planning for?

**Comment by jshenkman** [comment]
I need to talk about it with the designers in the vivid discussions, but I thought for the first step you will add the one we currently support? 

this one?
![image](https://user-images.githubusercontent.com/67224525/156361093-8016b99b-8d67-4c33-bf3c-27b5482e00f7.png)

**Comment by jshenkman** [comment]
After design discussion with designers, and agreeing on the desired design, this variant can be developed :) 

Design here.
Thank you!

**Comment by jshenkman** [comment]
![Screen Shot 2022-03-03 at 12 38 09](https://user-images.githubusercontent.com/67224525/156548169-93084a1c-e868-4975-b746-40e684c0fe3f.png)

Please notice the comment on the separator between the button-controls 
![Screen Shot 2022-03-03 at 12 38 19](https://user-images.githubusercontent.com/67224525/156548191-1227053f-7cc6-4190-bf8e-76fdbe6c3a95.png)

**Comment by rachelbt** [comment]
interesting article about - not every input that contains numbers should have an input type number:
https://kilianvalkhof.com/2022/css-html/are-you-sure-thats-a-number-input/
