### ISSUE TITLE
[textfield] appearance ghost support

### ISSUE THREAD

**Issue by jshenkman** [Vonage/vivid#1247]
Add to `text field` component ghost appearance, similar to the implementation in `select`.

Related to this issue https://github.com/Vonage/vivid-3/issues/87

**Comment by rachelbt** [comment]
@jshenkman can you please add design?
Are all the variation will get the ghost appearance?
what if theres no label or help text - how will the user will know where the field is? I assume there will be a question near by but still...

**Comment by yinonov** [comment]
in vivid `< v3.0.0` this can be applied by hardcoded css style. we'll improve with common mixin in vivid `next`

**Comment by rachelbt** [comment]
@jshenkman 
can you please have a look at the storybook to see if the ghost is OK:
https://tmp.dev.vivid.vonage.com/1293/index.html?path=/story/components-textfield--default&args=value:Initial+value;placeholder:Placeholder;appearance:ghost

You can set appearance:goest to all the variation using the controls:
![image](https://user-images.githubusercontent.com/7512792/166633917-2c829090-a2f9-4fce-93b8-4f2d71bae75d.png)

was not sure if we need a story for that or its just for internal use for this: https://github.com/Vonage/vivid-3/issues/87
