### ISSUE TITLE
vwc-textarea scroll bar in Windows looks bad

### ISSUE THREAD

**Issue by yonatanaftali** [Vonage/vivid#1258]
**Describe the bug**
Using <vwc-textarea> in Windows, when the user types long text, the scrollbar looks bad + there's a box-shaped object at the bottom of the scrollbar. On Mac, it looks well.

**To Reproduce**
Use <vwc-textarea> with long enough text in Windows.

**Expected behavior**
Should behave the same as in Mac.

**Screenshots**
Mac (good):
![image](https://user-images.githubusercontent.com/57040227/158376645-2e9f6b06-3d84-41a7-bb7e-472bcd621409.png)

Windows (~~bad~~ less pretty):
![image](https://user-images.githubusercontent.com/57040227/158376180-9204a390-77dc-4f16-9fa1-ee6b8b7881d3.png)

**Desktop:**
 - OS: Windows
 - Browser: Chrome

**Comment by yinonov** [comment]
these are OS/browsers' specifics. not styled by the component

**Comment by rachelbt** [comment]
@yinonov sure, but we can style them if we want :)

**Comment by yinonov** [comment]
> @yinonov sure, but we can style them if we want :) The question is if it worth the effort

this type of styling usually involve tweaking and hacks and are not throughly defined or specified.
The complexity out-cost the reward.

closing this as is not a component related issue. please reopen if you find it still needs attention
