### ISSUE TITLE
[Layout]: unwanted css-variable inheritance

### ISSUE THREAD

**Issue by rachelbt** [Vonage/vivid#1329]
**Describe the bug**
When using a custom css variable for setting costume column grid layout, the variable effects the nested `vwc-layout` as well

**To Reproduce**
1. use `vwc-layout` and set  a css-custom property using: `--layout-grid-template-columns` (say: -`-layout-grid-template-columns: 100px 400px;`)
2. nest another `vwc-layout` inside the `vwc-layout` with column-basis="block" (the bug happens even without it - but with block - you would expect the elements to pile up with 100% width)
3. See error

**Expected behavior**
that `--layout-grid-template-columns` will not affect nested `vwc-layout`

**Screenshots**
![image](https://user-images.githubusercontent.com/7512792/176772824-60a812b3-2247-4f85-9d36-beff839e32fa.png)

**Additional context**
Happens also in vivid-3

**Comment by yinonov** [comment]
experienced similar issue and added a section addressing it in https://modern-web.dev/guides/going-buildless/css/#inherited-values
until [registration of custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/@property) is supported, we can workaround it in authors scope by unsetting the `--layout-grid-template-columns`.

```html
<vwc-layout style="--layout-grid-template-columns: {whatever...}">
    <vwc-layout style="--layout-grid-template-columns: unset;">
        ...
```

**Comment by yinonov** [comment]
closing as there's no action item planned until browsers supports custom properties. please reopen if see fit

**Comment by rachelbt** [comment]
@yinonov - I'm wondering if we need to add it to the layout documentation... What do you think?

**Comment by yinonov** [comment]
> @yinonov - I'm wondering if we need to add it to the layout documentation... What do you think?

yes addressing the problem and a workaround can be a feasible alternative to resolve this.

this is my authoring so we can plainly copy & paste it

<img width="884" alt="image" src="https://user-images.githubusercontent.com/15140652/178140555-2dc2a87f-dc6f-467c-b419-bc6b778f5c30.png">

Then, due to lack of current support, add the option to unset variable on nested child
