### ISSUE TITLE
[Card] outdated doc: slot `actions`

### ISSUE THREAD

**Issue by k-paxian** [Vonage/vivid#1330]
https://vivid.vonage.com/?path=/story/components-card--introduction

**Screenshots**
![image](https://user-images.githubusercontent.com/18071010/177371441-15efe6f7-eacd-412f-810c-602bb2d36131.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/18071010/177371610-38511977-d1c5-4b9c-9a87-bc1f5a2ed534.png)

**Comment by yinonov** [comment]
Thanks @k-paxian. on its way 👆
