### ISSUE TITLE
[IconButton]: Add value assignable attribute

### ISSUE THREAD

**Issue by dvelluto** [Vonage/vivid#1346]
**Is your feature request related to a problem? Please describe.**
When we're using `vwc-icon-button` inside a `vwc-button-toggle` and we want a mutually exclusive behavior (e.g. if I click on A I toggle selection between A and B, same while clicking on B), we need to set the proper `value` on the button as we give the possible `values` to the button group.

**Describe the solution you'd like**
`html.button` has the `value` attribute, it would be nice to have it exposed also from `vwc-icon-button` like it's exposed by `vwc-button`

**Describe alternatives you've considered**
Temporary solution is force the attribute on the element, it's being passed down and works as intended.

**Comment by rinaok** [comment]
Hey @dvelluto , is this still an issue or we can close it?

**Comment by rinaok** [comment]
@dvelluto Thanks for the answer. Does your team still use vivid-2, or are you in the process of migrating to vivid-3?

**Comment by dvelluto** [comment]
we're still on vivid-2. Is this fixed on vivid-3 ? we can collect solved issues in vivid-3 to push for moving to the next version.

**Comment by rinaok** [comment]
Hi @dvelluto, because you already have a workaround for this issue, and vivid-2 is now only in maintenance mode, I'm closing this issue. It shouldn't be an issue when your team migrates to vivid-3. Thanks!
