### ISSUE TITLE
[IconButton / Icon] Add Support for Connotation.Warning

### ISSUE THREAD

**Issue by dvelluto** [Vonage/vivid#1348]
**Is your feature request related to a problem? Please describe.**
I would like to be able to assign all the connotation colors to a button with icon, but somehow the only one missing in the list is Warning (dark yellow)

**Describe the solution you'd like**
Add support for Connotation.Warning

**Describe alternatives you've considered**
In alternative I'm considering overriding the styles variables for this one icon I need to have dark yellow.
Adding `connotation="warning"` and 
```
'--connotation': 'rgb(250,159,0)'
```
to the inline styles does the trick.

**Additional context**
From figma of Team Dashboards Ui: 
![image](https://user-images.githubusercontent.com/57232860/197732115-3e4e20fc-a6d1-46c0-92f8-d862338e7a4f.png)

**Comment by rachelbt** [comment]
@dvelluto 
you will not be able to override the --connotation variable in the button.
However, you can assign colors to `vwc-icon `like this:
`<vwc-icon inline="" type="warning-solid" style="color: var(--vvd-color-warning)"></vwc-icon>`
If you are using the icon to trigger a tooltip - take in mind the [accessibility issue](you will not be able to override the --connotation variable in the button)

**Comment by dvelluto** [comment]
@rachelbt I'm using vivid via the [vonage/vivid-react](https://github.com/Vonage/vivid-react) wrappers, so maybe this could be a shortcut that we can do only with the wrappers. I assure you it's working ;)

**Comment by yinonov** [comment]
The reason not to support warning connotation is derived by the design spec. @dvelluto is there a design ure following that includes such style to an icon button?
We shouldn't rush resolving into workaround as the result would deviate from the design system guidelines

**Comment by dvelluto** [comment]
The design is using an Icon, the Icon Button need is to display the tooltip on top of it. 
From the figma for team-dashboards-ui: 
![image](https://user-images.githubusercontent.com/57232860/197948582-6f0dcc9e-a0ba-48d6-a3e9-935d6bc9ce05.png)

As I understand, the final solution would be to force color on the icon and warning connotation will not be implemented for the  icon-button. Thanks for the clarification and suggestion.
