### ISSUE TITLE
[Select] - Override displayed value

### ISSUE THREAD

**Issue by krzysiekwit2** [Vonage/vivid#1349]
Request from Team Spyro

**Need to achieve**

Need to achieve that effect with vivid-select:
<img width="183" alt="Screenshot 2022-10-27 at 13 09 59" src="https://user-images.githubusercontent.com/84602671/198269778-0cc5852b-e662-46e0-bac5-4e4f353e5eed.png">
(in square)
In Team dashboards MFE we need to display user presence same way as in contact pad.

**Solution**

The best solution for me would be a property like "overrideDisplayedValue" that could accept some html element.
Then i could manage displayed value by myself.

**Comment by yinonov** [comment]
can you please elaborate on the request?
The nearest plan regarding _**select**_ component, in [vivid@next](vonage/vivid-3), would be to align with recommended pattern and avoid opinionated implementation

**Comment by krzysiekwit2** [comment]
Okay sorry, so for example I have three values in select like:
- ready
- away
- break
and when user click on ready, I would like to display chosen value ready with green dot on left side.

Effect that i need to achieve.
<img width="186" alt="image" src="https://user-images.githubusercontent.com/84602671/198556975-bb5a3d95-66ce-41c4-8576-8c78dc82d714.png">

I need property that let me customise selected element.

**Comment by yinonov** [comment]
AFAIK this deviates from the design system spec. Is there a design you're following with this use-case?

**Comment by krzysiekwit2** [comment]
Sorry for late response, we decided that we gonna use some external library for that. 
I am closing that issue.

**Comment by yinonov** [comment]
I would suggest the alternative of conforming to the vonage look and feel. That's an objective we all should adopt. Deviating will only result in more tech debts
