### ISSUE TITLE
[Accessibility] Use REM instead of pixels for vivid CSS

### ISSUE THREAD

**Issue by acelletti** [Vonage/vivid#1362]
We are currently seeing that as we change the font size of our browser, all of the vivid components are not scaling with the change in size. 

This creates a weird effect where our website is mostly responsive, with the vivid components sticking out as too big / too small.

To reproduce simply change your browser font size and visit https://vivid.vonage.com/ to see that the page stays the same.

**Comment by acelletti** [comment]
<img width="1498" alt="Screenshot 2022-11-30 at 14 51 24" src="https://user-images.githubusercontent.com/37002976/204828145-129a30c1-eae0-47cb-a32d-1f1c719f50d4.png">

**Comment by yinonov** [comment]
It's been resolved

https://vivid.deno.dev/designs/design-tokens#typography
