### ISSUE TITLE
[Table] Table is not responsive on small screens

### ISSUE THREAD

**Issue by pytjiam** [Vonage/vivid#1371]
Table is not responsive on small screens, column is being cut off.

Desktop view:

<img width="1416" alt="Screenshot 2023-01-27 at 09 54 49" src="https://user-images.githubusercontent.com/109586875/215058234-ba127372-b677-4ccf-8b9f-6f985bd7791b.png">

Mobile view:

<img width="376" alt="Screenshot 2023-01-27 at 10 08 12" src="https://user-images.githubusercontent.com/109586875/215060788-d4e4bd56-a22f-4d9c-bff7-b3795fa33134.png">

HTML code:
```html
<table>
  <thead>
    <tr>
      <th>Field</th>
      <th>Example Value</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><code>iat</code></td>
      <td><code>1587494962</code></td>
      <td>The time at which the JWT was issued. Unix timestamp in SECONDS.</td>
    </tr>
    <tr>
      <td><code>jti</code></td>
      <td><code>c5ba8f24-1a14-4c10-bfdf-3fbe8ce511b5</code></td>
      <td>A unique ID for the JWT.</td>
    </tr>
    <tr>
      <td><code>iss</code></td>
      <td><code>Vonage</code></td>
      <td>The issuer of the JWT. This will always be 'Vonage'.</td>
    </tr>
    <tr>
      <td><code>payload_hash</code></td>
      <td><code>d6c0e74b5857df20e3b7e51b30c0c2a40ec73a77879b6f074ddc7a2317dd031b</code></td>
      <td>A SHA-256 hash of the request payload. Can be compared to the request payload to ensure it has not been tampered with during transit.</td>
    </tr>
    <tr>
      <td><code>api_key</code></td>
      <td><code>a1b2c3d</code></td>
      <td>The API key associated with the account that made the original request.</td>
    </tr>
    <tr>
      <td><code>application_id</code></td>
      <td><code>aaaaaaaa-bbbb-cccc-dddd-0123456789ab</code></td>
      <td>(Optional) The id of the application that made the original request if an application was used.</td>
    </tr>
  </tbody>
</table>
```

**Comment by yinonov** [comment]
responsive tables are a big challenge. solutions are mostly opinionated and require context of usage. a generic component cannot anticipate all cases. common practices require author's (YOUR) intervention (e.g. render less columns in narrow viewports etc')

This article can help understanding the challenge
https://www.smashingmagazine.com/2022/12/accessible-front-end-patterns-responsive-tables-part1/

Would you expect context in cells to trim?

**Comment by rinaok** [comment]
Hey @pytjiam ,
Could you please let me know if this is still an issue or if we can close it?
