### ISSUE TITLE
[vwc-list-item]: Text-Overflow Ellipsis Issue in Safari Browser

### ISSUE THREAD

**Issue by bchandel77** [Vonage/vivid#1373]
In Safari Browser, The vwc-list-items are giving ellipsis issue even when there is space for it.

<img width="375" alt="Screenshot 2023-03-15 at 4 33 44 PM" src="https://user-images.githubusercontent.com/108921736/225290567-2df36d2c-ee32-477f-ae05-cb4082b9fe51.png">

**Comment by rachelbt** [comment]
same issue as this: https://jira.vonage.com/browse/VIV-875
