### ISSUE TITLE
Text-Overflow Ellipsis Issue with vwc-list-item

### ISSUE THREAD

**Issue by rgupta4vonage** [Vonage/vivid#1374]
In any Browser, The vwc-list-items are giving ellipsis issue.

<img width="298" alt="image" src="https://user-images.githubusercontent.com/112708773/225294441-25a06d46-84ad-4ab9-be27-d3958dd346d7.png">

**Comment by rinaok** [comment]
Moved to a Jira ticket: https://jira.vonage.com/browse/VIV-895
