### ISSUE TITLE
[Popup] Arrow doesn't match position

### ISSUE THREAD

**Issue by dvelluto** [Vonage/vivid#1376]
**Describe the bug**
When a popup is open but there is not enough space for displaying in the corner where it was set to open, it is opening on the opposite side. The arrow is not following the "new" side taken.

**To Reproduce**
1. Go to ['vivid storybook'](https://dev.vivid.vonage.com/?path=/story/alpha-components-popup--alternate&args=open:true;arrow:true;corner:bottom;alternate:true)
2. Open the popup
3. Reduce the page size till the popup is showing in the upper side instead of the bottom

**Expected behavior**
The arrow should always point to anchor

**Screenshots**
![image](https://user-images.githubusercontent.com/57232860/227210344-a412c7c1-575f-4fd7-a419-db49f28793f1.png)

**Comment by rinaok** [comment]
Thank you for bringing the issue to our attention @dvelluto. The fix has been merged. 
https://github.com/Vonage/vivid/pull/1387

**Comment by dvelluto** [comment]
@rinaok is this going to be in 2.39 ? I see the behavior is fixed on dev storybook, but it's not yet live
