### ISSUE TITLE
vwc-data-grid - sort icon in first column cut off

### ISSUE THREAD

**Issue by adam-trojanowski** [Vonage/vivid#992]
**Describe the bug**
When using `vwc-data-grid` inside `vwc-expansion-panel`, setting the first column as sortable cuts of part of the sort icons.

**To Reproduce**

```
<vwc-expansion-panel open=''>
  <vwc-data-grid>
    <vwc-data-grid-column header='Users' sortable='' />
    <vwc-data-grid-column />
  </vwc-data-grid>
</vwc-expansion-panel>
```

Removing the expansion panel doesn't fix the issue.

**Expected behavior**
The icon should have enough space in the header to be properly displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/48203045/127307557-06c6edbd-7b57-4c81-ac13-59a27af37fa6.png)

**Desktop (please complete the following information):**
 - OS: macOS 11.5.1
 - Browser Chrome
 - Version 92.0.4515.107 (Official Build) (x86_64)
 - using @vonage/vwc-data-grid 2.15.0

**Comment by yinonov** [comment]
Fixed by #1070
